[features]
seeds = false
skip-lint = false
[programs.devnet]
pool_based_staking = "G2dDyhgXAFNAHvAn3VtLhTQvDEqDxBsDRooka5GERtYb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/work/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
